# Generated by Django 4.2.4 on 2024-01-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='Bankrupt',
            field=models.BooleanField(default=False),
        ),
    ]
