# Generated by Django 4.2.4 on 2024-01-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_brankrupt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Brankrupt',
            new_name='Bankrupt',
        ),
    ]
