# Generated by Django 4.2.4 on 2024-01-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_brankrupt_transaction_bankrupt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Bankrupt',
        ),
    ]
